name: bitewise_front
description: "BiteWise Frontend"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Ãcones
  cupertino_icons: ^1.0.8

  # Fonts e UI
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.0

  # Funcionalidades
  url_launcher: ^6.2.5
  dio: ^5.4.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/